services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ProjectManager
    volumes:
      - ./postgres:/var/lib/postgresql/data
  db-test:
    image: postgres:14.3
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD_TEST}
      POSTGRES_DB: ${DB_NAME_TEST}
    container_name: ProjectManagerTest